### PR TITLE
The fix that makes Ultimine work...

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**
...maybe... hopefully... *please*

(Actually it's confirmed working so good to go)

### CODE REVIEW

**Comment by choekstr** [comment]
I assume this fix that was committed 4 hours ago was in the version compiled and pushed 2 hours ago, 2.0-build.21, however still getting a crash loading it:

```
Stacktrace:
	at com.feed_the_beast.mods.ftbultimine.net.FTBUltimineNet.init(FTBUltimineNet.java:18) ~[?:1605.2.0-build.21] {re:classloading}
-- MOD ftbultimine --
Details:
	Mod File: ftb-ultimine-1605.2.0-build.21-forge.jar
	Failure message: FTB Ultimine (ftbultimine) has failed to load correctly
		java.lang.NoSuchMethodError: me.shedaniel.architectury.networking.NetworkChannel.register(Ljava/lang/Class;Ljava/util/function/BiConsumer;Ljava/util/function/Function;Ljava/util/function/BiConsumer;)V
	Mod Version: 1605.2.0-build.21
```

LMK if you need a full crashlog...

**Comment by MaxNeedsSnacks** [comment]
> I assume this fix that was committed 4 hours ago was in the version compiled and pushed 2 hours ago, 2.0-build.21, however still getting a crash loading it:
> 
> ```
> Stacktrace:
> 	at com.feed_the_beast.mods.ftbultimine.net.FTBUltimineNet.init(FTBUltimineNet.java:18) ~[?:1605.2.0-build.21] {re:classloading}
> -- MOD ftbultimine --
> Details:
> 	Mod File: ftb-ultimine-1605.2.0-build.21-forge.jar
> 	Failure message: FTB Ultimine (ftbultimine) has failed to load correctly
> 		java.lang.NoSuchMethodError: me.shedaniel.architectury.networking.NetworkChannel.register(Ljava/lang/Class;Ljava/util/function/BiConsumer;Ljava/util/function/Function;Ljava/util/function/BiConsumer;)V
> 	Mod Version: 1605.2.0-build.21
> ```
> 
> LMK if you need a full crashlog...

Do you have architectury-api installed?

**Comment by choekstr** [comment]
Yes, that is in this pack.  I assume that is a conflict?

**Comment by MaxNeedsSnacks** [comment]
It's not, but you should probably update it to the newest version

**Comment by choekstr** [comment]
yeah, just noticed it's newer.  stay tuned, trying now.

**Pull request merged**
