### PR TITLE
Added Mining Gadgets MK II and MK III to strict excluded tools tags 

### PR DESCRIPTION
**Pull request by NillerMedDild**
These are new-ish versions of the standard Mining Gadget

### CODE REVIEW

**Comment by MaxNeedsSnacks** [comment]
Mind PRing this to Mining Gadgets itself if you can? I wanted to actually clean up and remove foreign mod items from our own tag, and I'm sure @MichaelHillcox doesn't mind having this in MG itself either :p

**Comment by NillerMedDild** [comment]
Sure thing.

**Comment by NillerMedDild** [comment]
There you go: https://github.com/Direwolf20-MC/MiningGadgets/pull/160

**Comment by MaxNeedsSnacks** [comment]
Awesome, thanks a ton! Closing this then since it was superseded by that

**Pull request closed without merging**
